export enum NotificationType {
  PAYMENT_OVERDUE = 'payment_overdue',
  CONTRACT_EXPIRING = 'contract_expiring',
  CONTRACT_EXPIRED = 'contract_expired',
  CONTRACT_CREATED = 'contract_created',
  PAYMENT_REMINDER = 'payment_reminder',
  PAYMENT_RECEIVED = 'payment_received',
  CUSTOMER_CREATED = 'customer_created',
  ROOM_CREATED = 'room_created',
  ROOM_DELETED = 'room_deleted',
  WAREHOUSE_CREATED = 'warehouse_created',
  WAREHOUSE_DELETED = 'warehouse_deleted',
  STAFF_CREATED = 'staff_created',
  STAFF_DELETED = 'staff_deleted',
  TRANSPORTATION_JOB_CREATED = 'transportation_job_created',
  TRANSPORTATION_JOB_UPDATED = 'transportation_job_updated',
  SYSTEM = 'system',
}
