import { MigrationInterface, QueryRunner } from "typeorm";

export class AddPaymentTypeColumn1769996961114 implements MigrationInterface {
    name = 'AddPaymentTypeColumn1769996961114'

    public async up(queryRunner: QueryRunner): Promise<void> {
        const safeDropFK = async (table: string, fk: string) => {
            try {
                await queryRunner.query(`ALTER TABLE \`${table}\` DROP FOREIGN KEY \`${fk}\``);
            } catch (e) {}
        };
        const safeDropIndex = async (table: string, index: string, onTable: string) => {
            try {
                await queryRunner.query(`DROP INDEX \`${index}\` ON \`${onTable}\``);
            } catch (e) {}
        };

        await safeDropFK('users', 'FK_users_company');
        await safeDropFK('bank_accounts', 'FK_bank_accounts_company');
        await safeDropFK('customers', 'FK_customers_company');
        await safeDropFK('customers', 'FK_customers_user');
        await safeDropFK('payments', 'FK_payments_contract');
        await safeDropFK('contract_monthly_prices', 'FK_contract_monthly_prices_contract');
        await safeDropFK('contract_staff', 'FK_contract_staff_contract');
        await safeDropFK('contract_staff', 'FK_contract_staff_user');
        await safeDropFK('contracts', 'FK_contracts_customer');
        await safeDropFK('contracts', 'FK_contracts_room');
        await safeDropFK('contracts', 'FK_contracts_sold_by_user');
        await safeDropFK('items', 'FK_items_contract');
        await safeDropFK('items', 'FK_items_room');
        await safeDropFK('rooms', 'FK_rooms_warehouse');
        await safeDropFK('warehouses', 'FK_warehouses_company');
        await safeDropFK('transportation_job_staff', 'FK_transportation_job_staff_job');
        await safeDropFK('transportation_job_staff', 'FK_transportation_job_staff_user');
        await safeDropFK('transportation_jobs', 'FK_transportation_jobs_company');
        await safeDropFK('transportation_jobs', 'FK_transportation_jobs_customer');
        await safeDropFK('notifications', 'FK_notifications_customer');
        await safeDropFK('notifications', 'FK_notifications_user');
        await safeDropFK('company_paytr_settings', 'FK_paytr_settings_company');
        await safeDropFK('company_mail_settings', 'FK_company_mail_settings_company');

        await safeDropIndex('users', 'IDX_users_company', 'users');
        await safeDropIndex('users', 'UQ_users_email', 'users');
        await safeDropIndex('bank_accounts', 'IDX_bank_accounts_company', 'bank_accounts');
        await safeDropIndex('companies', 'UQ_companies_slug', 'companies');
        await safeDropIndex('customers', 'IDX_customers_company', 'customers');
        await safeDropIndex('customers', 'IDX_customers_user', 'customers');
        await safeDropIndex('payments', 'IDX_payments_contract', 'payments');
        await safeDropIndex('payments', 'UQ_payments_number', 'payments');
        await safeDropIndex('contract_monthly_prices', 'IDX_contract_monthly_prices_contract', 'contract_monthly_prices');
        await safeDropIndex('contract_monthly_prices', 'IDX_contract_monthly_prices_month', 'contract_monthly_prices');
        await safeDropIndex('contract_staff', 'IDX_contract_staff_contract', 'contract_staff');
        await safeDropIndex('contract_staff', 'IDX_contract_staff_user', 'contract_staff');
        await safeDropIndex('contract_staff', 'UQ_contract_staff', 'contract_staff');
        await safeDropIndex('contracts', 'IDX_contracts_customer', 'contracts');
        await safeDropIndex('contracts', 'IDX_contracts_room', 'contracts');
        await safeDropIndex('contracts', 'UQ_contracts_number', 'contracts');
        await safeDropIndex('items', 'IDX_items_contract', 'items');
        await safeDropIndex('items', 'IDX_items_room', 'items');
        await safeDropIndex('rooms', 'IDX_rooms_warehouse', 'rooms');
        await safeDropIndex('warehouses', 'IDX_warehouses_company', 'warehouses');
        await safeDropIndex('transportation_job_staff', 'IDX_transportation_job_staff_job', 'transportation_job_staff');
        await safeDropIndex('transportation_job_staff', 'IDX_transportation_job_staff_user', 'transportation_job_staff');
        await safeDropIndex('transportation_jobs', 'IDX_transportation_jobs_company', 'transportation_jobs');
        await safeDropIndex('transportation_jobs', 'IDX_transportation_jobs_customer', 'transportation_jobs');
        await safeDropIndex('notifications', 'IDX_notifications_customer', 'notifications');
        await safeDropIndex('notifications', 'IDX_notifications_user', 'notifications');
        await safeDropIndex('company_paytr_settings', 'IDX_paytr_settings_company', 'company_paytr_settings');
        await safeDropIndex('company_paytr_settings', 'UQ_paytr_settings_company', 'company_paytr_settings');
        await safeDropIndex('company_mail_settings', 'UQ_company_mail_settings_company', 'company_mail_settings');
        await queryRunner.query(`CREATE TABLE \`company_sms_settings\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`company_id\` varchar(255) NOT NULL, \`username\` varchar(255) NULL, \`password\` varchar(255) NULL, \`sender_id\` varchar(50) NULL, \`api_url\` varchar(255) NULL, \`is_active\` tinyint NOT NULL DEFAULT 0, \`test_mode\` tinyint NOT NULL DEFAULT 0, UNIQUE INDEX \`REL_d2b08509989c8a9869b417f48f\` (\`company_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`payments\` ADD \`type\` enum ('warehouse', 'transportation', 'other') NOT NULL DEFAULT 'warehouse'`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`id\` varchar(36) NOT NULL PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`created_at\` \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`updated_at\` \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`role\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`role\` enum ('super_admin', 'company_owner', 'company_staff', 'data_entry', 'accounting', 'customer') NOT NULL DEFAULT 'customer'`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`company_id\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`company_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`bank_accounts\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`bank_accounts\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`bank_accounts\` ADD \`id\` varchar(36) NOT NULL PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`bank_accounts\` CHANGE \`created_at\` \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`bank_accounts\` CHANGE \`updated_at\` \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`bank_accounts\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`bank_accounts\` DROP COLUMN \`company_id\``);
        await queryRunner.query(`ALTER TABLE \`bank_accounts\` ADD \`company_id\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`companies\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`companies\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`companies\` ADD \`id\` varchar(36) NOT NULL PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`companies\` CHANGE \`created_at\` \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`companies\` CHANGE \`updated_at\` \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`companies\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`companies\` CHANGE \`slug\` \`slug\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`companies\` ADD UNIQUE INDEX \`IDX_b28b07d25e4324eee577de5496\` (\`slug\`)`);
        await queryRunner.query(`ALTER TABLE \`customers\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`customers\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`customers\` ADD \`id\` varchar(36) NOT NULL PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`customers\` CHANGE \`created_at\` \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`customers\` CHANGE \`updated_at\` \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`customers\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`customers\` DROP COLUMN \`user_id\``);
        await queryRunner.query(`ALTER TABLE \`customers\` ADD \`user_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`customers\` DROP COLUMN \`company_id\``);
        await queryRunner.query(`ALTER TABLE \`customers\` ADD \`company_id\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`payments\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`payments\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`payments\` ADD \`id\` varchar(36) NOT NULL PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`created_at\` \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`updated_at\` \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`payment_number\` \`payment_number\` varchar(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`payments\` ADD UNIQUE INDEX \`IDX_37f40df34aab6084881c0ceebd\` (\`payment_number\`)`);
        await queryRunner.query(`ALTER TABLE \`payments\` DROP COLUMN \`contract_id\``);
        await queryRunner.query(`ALTER TABLE \`payments\` ADD \`contract_id\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`payments\` DROP COLUMN \`status\``);
        await queryRunner.query(`ALTER TABLE \`payments\` ADD \`status\` enum ('pending', 'paid', 'overdue', 'cancelled') NOT NULL DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE \`payments\` DROP COLUMN \`bank_account_id\``);
        await queryRunner.query(`ALTER TABLE \`payments\` ADD \`bank_account_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`contract_monthly_prices\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`contract_monthly_prices\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`contract_monthly_prices\` ADD \`id\` varchar(36) NOT NULL PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`contract_monthly_prices\` CHANGE \`created_at\` \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`contract_monthly_prices\` CHANGE \`updated_at\` \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`contract_monthly_prices\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`contract_monthly_prices\` DROP COLUMN \`contract_id\``);
        await queryRunner.query(`ALTER TABLE \`contract_monthly_prices\` ADD \`contract_id\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`contract_staff\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`contract_staff\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`contract_staff\` ADD \`id\` varchar(36) NOT NULL PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`contract_staff\` CHANGE \`created_at\` \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`contract_staff\` CHANGE \`updated_at\` \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`contract_staff\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`contract_staff\` DROP COLUMN \`contract_id\``);
        await queryRunner.query(`ALTER TABLE \`contract_staff\` ADD \`contract_id\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`contract_staff\` DROP COLUMN \`user_id\``);
        await queryRunner.query(`ALTER TABLE \`contract_staff\` ADD \`user_id\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`contracts\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`contracts\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`contracts\` ADD \`id\` varchar(36) NOT NULL PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`contracts\` CHANGE \`created_at\` \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`contracts\` CHANGE \`updated_at\` \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`contracts\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`contracts\` CHANGE \`contract_number\` \`contract_number\` varchar(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`contracts\` ADD UNIQUE INDEX \`IDX_db84c172dc74e6271e614b68fb\` (\`contract_number\`)`);
        await queryRunner.query(`ALTER TABLE \`contracts\` DROP COLUMN \`customer_id\``);
        await queryRunner.query(`ALTER TABLE \`contracts\` ADD \`customer_id\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`contracts\` DROP COLUMN \`room_id\``);
        await queryRunner.query(`ALTER TABLE \`contracts\` ADD \`room_id\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`contracts\` DROP COLUMN \`sold_by_user_id\``);
        await queryRunner.query(`ALTER TABLE \`contracts\` ADD \`sold_by_user_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`items\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`items\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`items\` ADD \`id\` varchar(36) NOT NULL PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`items\` CHANGE \`created_at\` \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`items\` CHANGE \`updated_at\` \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`items\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`items\` DROP COLUMN \`room_id\``);
        await queryRunner.query(`ALTER TABLE \`items\` ADD \`room_id\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`items\` DROP COLUMN \`contract_id\``);
        await queryRunner.query(`ALTER TABLE \`items\` ADD \`contract_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`rooms\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`rooms\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`rooms\` ADD \`id\` varchar(36) NOT NULL PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`rooms\` CHANGE \`created_at\` \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`rooms\` CHANGE \`updated_at\` \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`rooms\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`rooms\` DROP COLUMN \`warehouse_id\``);
        await queryRunner.query(`ALTER TABLE \`rooms\` ADD \`warehouse_id\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`rooms\` DROP COLUMN \`status\``);
        await queryRunner.query(`ALTER TABLE \`rooms\` ADD \`status\` enum ('empty', 'occupied', 'reserved', 'locked') NOT NULL DEFAULT 'empty'`);
        await queryRunner.query(`ALTER TABLE \`warehouses\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`warehouses\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`warehouses\` ADD \`id\` varchar(36) NOT NULL PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`warehouses\` CHANGE \`created_at\` \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`warehouses\` CHANGE \`updated_at\` \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`warehouses\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`warehouses\` DROP COLUMN \`company_id\``);
        await queryRunner.query(`ALTER TABLE \`warehouses\` ADD \`company_id\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`transportation_job_staff\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`transportation_job_staff\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`transportation_job_staff\` ADD \`id\` varchar(36) NOT NULL PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`transportation_job_staff\` CHANGE \`created_at\` \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`transportation_job_staff\` CHANGE \`updated_at\` \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`transportation_job_staff\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`transportation_job_staff\` DROP COLUMN \`transportation_job_id\``);
        await queryRunner.query(`ALTER TABLE \`transportation_job_staff\` ADD \`transportation_job_id\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`transportation_job_staff\` DROP COLUMN \`user_id\``);
        await queryRunner.query(`ALTER TABLE \`transportation_job_staff\` ADD \`user_id\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`transportation_jobs\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`transportation_jobs\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`transportation_jobs\` ADD \`id\` varchar(36) NOT NULL PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`transportation_jobs\` CHANGE \`created_at\` \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`transportation_jobs\` CHANGE \`updated_at\` \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`transportation_jobs\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`transportation_jobs\` DROP COLUMN \`company_id\``);
        await queryRunner.query(`ALTER TABLE \`transportation_jobs\` ADD \`company_id\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`transportation_jobs\` DROP COLUMN \`customer_id\``);
        await queryRunner.query(`ALTER TABLE \`transportation_jobs\` ADD \`customer_id\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`transportation_jobs\` CHANGE \`is_paid\` \`is_paid\` tinyint NOT NULL DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE \`notifications\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`notifications\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`notifications\` ADD \`id\` varchar(36) NOT NULL PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`notifications\` CHANGE \`created_at\` \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`notifications\` CHANGE \`updated_at\` \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`notifications\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`notifications\` DROP COLUMN \`user_id\``);
        await queryRunner.query(`ALTER TABLE \`notifications\` ADD \`user_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`notifications\` DROP COLUMN \`customer_id\``);
        await queryRunner.query(`ALTER TABLE \`notifications\` ADD \`customer_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`notifications\` DROP COLUMN \`type\``);
        await queryRunner.query(`ALTER TABLE \`notifications\` ADD \`type\` enum ('payment_overdue', 'contract_expiring', 'contract_expired', 'contract_created', 'payment_reminder', 'payment_received', 'customer_created', 'room_created', 'room_deleted', 'warehouse_created', 'warehouse_deleted', 'staff_created', 'staff_deleted', 'transportation_job_created', 'transportation_job_updated', 'system') NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`company_paytr_settings\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`company_paytr_settings\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`company_paytr_settings\` ADD \`id\` varchar(36) NOT NULL PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`company_paytr_settings\` CHANGE \`created_at\` \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`company_paytr_settings\` CHANGE \`updated_at\` \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`company_paytr_settings\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`company_paytr_settings\` DROP COLUMN \`company_id\``);
        await queryRunner.query(`ALTER TABLE \`company_paytr_settings\` ADD \`company_id\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`company_paytr_settings\` ADD UNIQUE INDEX \`IDX_edf59737da13f03e9faa419743\` (\`company_id\`)`);
        await queryRunner.query(`ALTER TABLE \`company_mail_settings\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`company_mail_settings\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`company_mail_settings\` ADD \`id\` varchar(36) NOT NULL PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`company_mail_settings\` CHANGE \`created_at\` \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`company_mail_settings\` CHANGE \`updated_at\` \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`company_mail_settings\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`company_mail_settings\` DROP COLUMN \`company_id\``);
        await queryRunner.query(`ALTER TABLE \`company_mail_settings\` ADD \`company_id\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`company_mail_settings\` ADD UNIQUE INDEX \`IDX_eb8bc07a81caea2c83e486a25f\` (\`company_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`REL_edf59737da13f03e9faa419743\` ON \`company_paytr_settings\` (\`company_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`REL_eb8bc07a81caea2c83e486a25f\` ON \`company_mail_settings\` (\`company_id\`)`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD CONSTRAINT \`FK_7ae6334059289559722437bcc1c\` FOREIGN KEY (\`company_id\`) REFERENCES \`companies\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`bank_accounts\` ADD CONSTRAINT \`FK_869d5463de72be0afa52f0859e8\` FOREIGN KEY (\`company_id\`) REFERENCES \`companies\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`customers\` ADD CONSTRAINT \`FK_11d81cd7be87b6f8865b0cf7661\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`payments\` ADD CONSTRAINT \`FK_52fc2356fb8c211c93d4b1496f3\` FOREIGN KEY (\`contract_id\`) REFERENCES \`contracts\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`payments\` ADD CONSTRAINT \`FK_00ec82cb228fb85ddbe768fb6d4\` FOREIGN KEY (\`bank_account_id\`) REFERENCES \`bank_accounts\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`contract_monthly_prices\` ADD CONSTRAINT \`FK_f50cfcdf9a2786b227ad3db00c6\` FOREIGN KEY (\`contract_id\`) REFERENCES \`contracts\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`contract_staff\` ADD CONSTRAINT \`FK_618a7585cbb2740668221784703\` FOREIGN KEY (\`contract_id\`) REFERENCES \`contracts\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`contract_staff\` ADD CONSTRAINT \`FK_99cc0fdc6261f9d0bcf13b65992\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`contracts\` ADD CONSTRAINT \`FK_2e66f7950711366031e3200413d\` FOREIGN KEY (\`customer_id\`) REFERENCES \`customers\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`contracts\` ADD CONSTRAINT \`FK_36b16ffbd8846bd80f7ae72241d\` FOREIGN KEY (\`room_id\`) REFERENCES \`rooms\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`contracts\` ADD CONSTRAINT \`FK_5dd5738dac15ca2687138a947fb\` FOREIGN KEY (\`sold_by_user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`items\` ADD CONSTRAINT \`FK_e4b5876b9dc744b77ecfb7f0eef\` FOREIGN KEY (\`room_id\`) REFERENCES \`rooms\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`items\` ADD CONSTRAINT \`FK_f64f3ab93032cbb4596c541d5ac\` FOREIGN KEY (\`contract_id\`) REFERENCES \`contracts\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`rooms\` ADD CONSTRAINT \`FK_b1fd3fe7b80a5176ce8d8659d3f\` FOREIGN KEY (\`warehouse_id\`) REFERENCES \`warehouses\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`warehouses\` ADD CONSTRAINT \`FK_3fcbfd5832b46945f514a7d1f56\` FOREIGN KEY (\`company_id\`) REFERENCES \`companies\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`transportation_job_staff\` ADD CONSTRAINT \`FK_f090ca206307005520fa973a860\` FOREIGN KEY (\`transportation_job_id\`) REFERENCES \`transportation_jobs\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`transportation_job_staff\` ADD CONSTRAINT \`FK_b59b22e5da96680bc7d7ed8a522\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`transportation_jobs\` ADD CONSTRAINT \`FK_5bd54300645fa99e0b115c7362f\` FOREIGN KEY (\`customer_id\`) REFERENCES \`customers\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`notifications\` ADD CONSTRAINT \`FK_9a8a82462cab47c73d25f49261f\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`notifications\` ADD CONSTRAINT \`FK_b55350bc786b052e8523f313b9a\` FOREIGN KEY (\`customer_id\`) REFERENCES \`customers\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`company_sms_settings\` ADD CONSTRAINT \`FK_d2b08509989c8a9869b417f48f1\` FOREIGN KEY (\`company_id\`) REFERENCES \`companies\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`company_paytr_settings\` ADD CONSTRAINT \`FK_edf59737da13f03e9faa4197433\` FOREIGN KEY (\`company_id\`) REFERENCES \`companies\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`company_mail_settings\` ADD CONSTRAINT \`FK_eb8bc07a81caea2c83e486a25f3\` FOREIGN KEY (\`company_id\`) REFERENCES \`companies\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`company_mail_settings\` DROP FOREIGN KEY \`FK_eb8bc07a81caea2c83e486a25f3\``);
        await queryRunner.query(`ALTER TABLE \`company_paytr_settings\` DROP FOREIGN KEY \`FK_edf59737da13f03e9faa4197433\``);
        await queryRunner.query(`ALTER TABLE \`company_sms_settings\` DROP FOREIGN KEY \`FK_d2b08509989c8a9869b417f48f1\``);
        await queryRunner.query(`ALTER TABLE \`notifications\` DROP FOREIGN KEY \`FK_b55350bc786b052e8523f313b9a\``);
        await queryRunner.query(`ALTER TABLE \`notifications\` DROP FOREIGN KEY \`FK_9a8a82462cab47c73d25f49261f\``);
        await queryRunner.query(`ALTER TABLE \`transportation_jobs\` DROP FOREIGN KEY \`FK_5bd54300645fa99e0b115c7362f\``);
        await queryRunner.query(`ALTER TABLE \`transportation_job_staff\` DROP FOREIGN KEY \`FK_b59b22e5da96680bc7d7ed8a522\``);
        await queryRunner.query(`ALTER TABLE \`transportation_job_staff\` DROP FOREIGN KEY \`FK_f090ca206307005520fa973a860\``);
        await queryRunner.query(`ALTER TABLE \`warehouses\` DROP FOREIGN KEY \`FK_3fcbfd5832b46945f514a7d1f56\``);
        await queryRunner.query(`ALTER TABLE \`rooms\` DROP FOREIGN KEY \`FK_b1fd3fe7b80a5176ce8d8659d3f\``);
        await queryRunner.query(`ALTER TABLE \`items\` DROP FOREIGN KEY \`FK_f64f3ab93032cbb4596c541d5ac\``);
        await queryRunner.query(`ALTER TABLE \`items\` DROP FOREIGN KEY \`FK_e4b5876b9dc744b77ecfb7f0eef\``);
        await queryRunner.query(`ALTER TABLE \`contracts\` DROP FOREIGN KEY \`FK_5dd5738dac15ca2687138a947fb\``);
        await queryRunner.query(`ALTER TABLE \`contracts\` DROP FOREIGN KEY \`FK_36b16ffbd8846bd80f7ae72241d\``);
        await queryRunner.query(`ALTER TABLE \`contracts\` DROP FOREIGN KEY \`FK_2e66f7950711366031e3200413d\``);
        await queryRunner.query(`ALTER TABLE \`contract_staff\` DROP FOREIGN KEY \`FK_99cc0fdc6261f9d0bcf13b65992\``);
        await queryRunner.query(`ALTER TABLE \`contract_staff\` DROP FOREIGN KEY \`FK_618a7585cbb2740668221784703\``);
        await queryRunner.query(`ALTER TABLE \`contract_monthly_prices\` DROP FOREIGN KEY \`FK_f50cfcdf9a2786b227ad3db00c6\``);
        await queryRunner.query(`ALTER TABLE \`payments\` DROP FOREIGN KEY \`FK_00ec82cb228fb85ddbe768fb6d4\``);
        await queryRunner.query(`ALTER TABLE \`payments\` DROP FOREIGN KEY \`FK_52fc2356fb8c211c93d4b1496f3\``);
        await queryRunner.query(`ALTER TABLE \`customers\` DROP FOREIGN KEY \`FK_11d81cd7be87b6f8865b0cf7661\``);
        await queryRunner.query(`ALTER TABLE \`bank_accounts\` DROP FOREIGN KEY \`FK_869d5463de72be0afa52f0859e8\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP FOREIGN KEY \`FK_7ae6334059289559722437bcc1c\``);
        await queryRunner.query(`DROP INDEX \`REL_eb8bc07a81caea2c83e486a25f\` ON \`company_mail_settings\``);
        await queryRunner.query(`DROP INDEX \`REL_edf59737da13f03e9faa419743\` ON \`company_paytr_settings\``);
        await queryRunner.query(`ALTER TABLE \`company_mail_settings\` DROP INDEX \`IDX_eb8bc07a81caea2c83e486a25f\``);
        await queryRunner.query(`ALTER TABLE \`company_mail_settings\` DROP COLUMN \`company_id\``);
        await queryRunner.query(`ALTER TABLE \`company_mail_settings\` ADD \`company_id\` char(36) COLLATE "utf8mb4_unicode_ci" NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`company_mail_settings\` CHANGE \`deleted_at\` \`deleted_at\` datetime(0) NULL`);
        await queryRunner.query(`ALTER TABLE \`company_mail_settings\` CHANGE \`updated_at\` \`updated_at\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`company_mail_settings\` CHANGE \`created_at\` \`created_at\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`company_mail_settings\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`company_mail_settings\` ADD \`id\` char(36) COLLATE "utf8mb4_unicode_ci" NOT NULL DEFAULT 'uuid()'`);
        await queryRunner.query(`ALTER TABLE \`company_mail_settings\` ADD PRIMARY KEY (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`company_paytr_settings\` DROP INDEX \`IDX_edf59737da13f03e9faa419743\``);
        await queryRunner.query(`ALTER TABLE \`company_paytr_settings\` DROP COLUMN \`company_id\``);
        await queryRunner.query(`ALTER TABLE \`company_paytr_settings\` ADD \`company_id\` char(36) COLLATE "utf8mb4_unicode_ci" NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`company_paytr_settings\` CHANGE \`deleted_at\` \`deleted_at\` datetime(0) NULL`);
        await queryRunner.query(`ALTER TABLE \`company_paytr_settings\` CHANGE \`updated_at\` \`updated_at\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`company_paytr_settings\` CHANGE \`created_at\` \`created_at\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`company_paytr_settings\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`company_paytr_settings\` ADD \`id\` char(36) COLLATE "utf8mb4_unicode_ci" NOT NULL DEFAULT 'uuid()'`);
        await queryRunner.query(`ALTER TABLE \`company_paytr_settings\` ADD PRIMARY KEY (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`notifications\` DROP COLUMN \`type\``);
        await queryRunner.query(`ALTER TABLE \`notifications\` ADD \`type\` varchar(50) COLLATE "utf8mb4_unicode_ci" NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`notifications\` DROP COLUMN \`customer_id\``);
        await queryRunner.query(`ALTER TABLE \`notifications\` ADD \`customer_id\` char(36) COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`notifications\` DROP COLUMN \`user_id\``);
        await queryRunner.query(`ALTER TABLE \`notifications\` ADD \`user_id\` char(36) COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`notifications\` CHANGE \`deleted_at\` \`deleted_at\` datetime(0) NULL`);
        await queryRunner.query(`ALTER TABLE \`notifications\` CHANGE \`updated_at\` \`updated_at\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`notifications\` CHANGE \`created_at\` \`created_at\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`notifications\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`notifications\` ADD \`id\` char(36) COLLATE "utf8mb4_unicode_ci" NOT NULL DEFAULT 'uuid()'`);
        await queryRunner.query(`ALTER TABLE \`notifications\` ADD PRIMARY KEY (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`transportation_jobs\` CHANGE \`is_paid\` \`is_paid\` tinyint NOT NULL COMMENT 'Ã–deme alÄ±ndÄ± mÄ±?' DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`transportation_jobs\` DROP COLUMN \`customer_id\``);
        await queryRunner.query(`ALTER TABLE \`transportation_jobs\` ADD \`customer_id\` char(36) COLLATE "utf8mb4_unicode_ci" NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`transportation_jobs\` DROP COLUMN \`company_id\``);
        await queryRunner.query(`ALTER TABLE \`transportation_jobs\` ADD \`company_id\` char(36) COLLATE "utf8mb4_unicode_ci" NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`transportation_jobs\` CHANGE \`deleted_at\` \`deleted_at\` datetime(0) NULL`);
        await queryRunner.query(`ALTER TABLE \`transportation_jobs\` CHANGE \`updated_at\` \`updated_at\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`transportation_jobs\` CHANGE \`created_at\` \`created_at\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`transportation_jobs\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`transportation_jobs\` ADD \`id\` char(36) COLLATE "utf8mb4_unicode_ci" NOT NULL DEFAULT 'uuid()'`);
        await queryRunner.query(`ALTER TABLE \`transportation_jobs\` ADD PRIMARY KEY (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`transportation_job_staff\` DROP COLUMN \`user_id\``);
        await queryRunner.query(`ALTER TABLE \`transportation_job_staff\` ADD \`user_id\` char(36) COLLATE "utf8mb4_unicode_ci" NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`transportation_job_staff\` DROP COLUMN \`transportation_job_id\``);
        await queryRunner.query(`ALTER TABLE \`transportation_job_staff\` ADD \`transportation_job_id\` char(36) COLLATE "utf8mb4_unicode_ci" NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`transportation_job_staff\` CHANGE \`deleted_at\` \`deleted_at\` datetime(0) NULL`);
        await queryRunner.query(`ALTER TABLE \`transportation_job_staff\` CHANGE \`updated_at\` \`updated_at\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`transportation_job_staff\` CHANGE \`created_at\` \`created_at\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`transportation_job_staff\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`transportation_job_staff\` ADD \`id\` char(36) COLLATE "utf8mb4_unicode_ci" NOT NULL DEFAULT 'uuid()'`);
        await queryRunner.query(`ALTER TABLE \`transportation_job_staff\` ADD PRIMARY KEY (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`warehouses\` DROP COLUMN \`company_id\``);
        await queryRunner.query(`ALTER TABLE \`warehouses\` ADD \`company_id\` char(36) COLLATE "utf8mb4_unicode_ci" NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`warehouses\` CHANGE \`deleted_at\` \`deleted_at\` datetime(0) NULL`);
        await queryRunner.query(`ALTER TABLE \`warehouses\` CHANGE \`updated_at\` \`updated_at\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`warehouses\` CHANGE \`created_at\` \`created_at\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`warehouses\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`warehouses\` ADD \`id\` char(36) COLLATE "utf8mb4_unicode_ci" NOT NULL DEFAULT 'uuid()'`);
        await queryRunner.query(`ALTER TABLE \`warehouses\` ADD PRIMARY KEY (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`rooms\` DROP COLUMN \`status\``);
        await queryRunner.query(`ALTER TABLE \`rooms\` ADD \`status\` varchar(50) COLLATE "utf8mb4_unicode_ci" NOT NULL DEFAULT 'empty'`);
        await queryRunner.query(`ALTER TABLE \`rooms\` DROP COLUMN \`warehouse_id\``);
        await queryRunner.query(`ALTER TABLE \`rooms\` ADD \`warehouse_id\` char(36) COLLATE "utf8mb4_unicode_ci" NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`rooms\` CHANGE \`deleted_at\` \`deleted_at\` datetime(0) NULL`);
        await queryRunner.query(`ALTER TABLE \`rooms\` CHANGE \`updated_at\` \`updated_at\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`rooms\` CHANGE \`created_at\` \`created_at\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`rooms\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`rooms\` ADD \`id\` char(36) COLLATE "utf8mb4_unicode_ci" NOT NULL DEFAULT 'uuid()'`);
        await queryRunner.query(`ALTER TABLE \`rooms\` ADD PRIMARY KEY (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`items\` DROP COLUMN \`contract_id\``);
        await queryRunner.query(`ALTER TABLE \`items\` ADD \`contract_id\` char(36) COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`items\` DROP COLUMN \`room_id\``);
        await queryRunner.query(`ALTER TABLE \`items\` ADD \`room_id\` char(36) COLLATE "utf8mb4_unicode_ci" NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`items\` CHANGE \`deleted_at\` \`deleted_at\` datetime(0) NULL`);
        await queryRunner.query(`ALTER TABLE \`items\` CHANGE \`updated_at\` \`updated_at\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`items\` CHANGE \`created_at\` \`created_at\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`items\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`items\` ADD \`id\` char(36) COLLATE "utf8mb4_unicode_ci" NOT NULL DEFAULT 'uuid()'`);
        await queryRunner.query(`ALTER TABLE \`items\` ADD PRIMARY KEY (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`contracts\` DROP COLUMN \`sold_by_user_id\``);
        await queryRunner.query(`ALTER TABLE \`contracts\` ADD \`sold_by_user_id\` char(36) COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`contracts\` DROP COLUMN \`room_id\``);
        await queryRunner.query(`ALTER TABLE \`contracts\` ADD \`room_id\` char(36) COLLATE "utf8mb4_unicode_ci" NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`contracts\` DROP COLUMN \`customer_id\``);
        await queryRunner.query(`ALTER TABLE \`contracts\` ADD \`customer_id\` char(36) COLLATE "utf8mb4_unicode_ci" NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`contracts\` DROP INDEX \`IDX_db84c172dc74e6271e614b68fb\``);
        await queryRunner.query(`ALTER TABLE \`contracts\` CHANGE \`contract_number\` \`contract_number\` varchar(100) COLLATE "utf8mb4_unicode_ci" NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`contracts\` CHANGE \`deleted_at\` \`deleted_at\` datetime(0) NULL`);
        await queryRunner.query(`ALTER TABLE \`contracts\` CHANGE \`updated_at\` \`updated_at\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`contracts\` CHANGE \`created_at\` \`created_at\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`contracts\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`contracts\` ADD \`id\` char(36) COLLATE "utf8mb4_unicode_ci" NOT NULL DEFAULT 'uuid()'`);
        await queryRunner.query(`ALTER TABLE \`contracts\` ADD PRIMARY KEY (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`contract_staff\` DROP COLUMN \`user_id\``);
        await queryRunner.query(`ALTER TABLE \`contract_staff\` ADD \`user_id\` char(36) COLLATE "utf8mb4_unicode_ci" NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`contract_staff\` DROP COLUMN \`contract_id\``);
        await queryRunner.query(`ALTER TABLE \`contract_staff\` ADD \`contract_id\` char(36) COLLATE "utf8mb4_unicode_ci" NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`contract_staff\` CHANGE \`deleted_at\` \`deleted_at\` datetime(0) NULL`);
        await queryRunner.query(`ALTER TABLE \`contract_staff\` CHANGE \`updated_at\` \`updated_at\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`contract_staff\` CHANGE \`created_at\` \`created_at\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`contract_staff\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`contract_staff\` ADD \`id\` char(36) COLLATE "utf8mb4_unicode_ci" NOT NULL DEFAULT 'uuid()'`);
        await queryRunner.query(`ALTER TABLE \`contract_staff\` ADD PRIMARY KEY (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`contract_monthly_prices\` DROP COLUMN \`contract_id\``);
        await queryRunner.query(`ALTER TABLE \`contract_monthly_prices\` ADD \`contract_id\` char(36) COLLATE "utf8mb4_unicode_ci" NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`contract_monthly_prices\` CHANGE \`deleted_at\` \`deleted_at\` datetime(0) NULL`);
        await queryRunner.query(`ALTER TABLE \`contract_monthly_prices\` CHANGE \`updated_at\` \`updated_at\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`contract_monthly_prices\` CHANGE \`created_at\` \`created_at\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`contract_monthly_prices\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`contract_monthly_prices\` ADD \`id\` char(36) COLLATE "utf8mb4_unicode_ci" NOT NULL DEFAULT 'uuid()'`);
        await queryRunner.query(`ALTER TABLE \`contract_monthly_prices\` ADD PRIMARY KEY (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`payments\` DROP COLUMN \`bank_account_id\``);
        await queryRunner.query(`ALTER TABLE \`payments\` ADD \`bank_account_id\` char(36) COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`payments\` DROP COLUMN \`status\``);
        await queryRunner.query(`ALTER TABLE \`payments\` ADD \`status\` varchar(50) COLLATE "utf8mb4_unicode_ci" NOT NULL DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE \`payments\` DROP COLUMN \`contract_id\``);
        await queryRunner.query(`ALTER TABLE \`payments\` ADD \`contract_id\` char(36) COLLATE "utf8mb4_unicode_ci" NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`payments\` DROP INDEX \`IDX_37f40df34aab6084881c0ceebd\``);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`payment_number\` \`payment_number\` varchar(100) COLLATE "utf8mb4_unicode_ci" NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`deleted_at\` \`deleted_at\` datetime(0) NULL`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`updated_at\` \`updated_at\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`created_at\` \`created_at\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`payments\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`payments\` ADD \`id\` char(36) COLLATE "utf8mb4_unicode_ci" NOT NULL DEFAULT 'uuid()'`);
        await queryRunner.query(`ALTER TABLE \`payments\` ADD PRIMARY KEY (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`customers\` DROP COLUMN \`company_id\``);
        await queryRunner.query(`ALTER TABLE \`customers\` ADD \`company_id\` char(36) COLLATE "utf8mb4_unicode_ci" NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`customers\` DROP COLUMN \`user_id\``);
        await queryRunner.query(`ALTER TABLE \`customers\` ADD \`user_id\` char(36) COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`customers\` CHANGE \`deleted_at\` \`deleted_at\` datetime(0) NULL`);
        await queryRunner.query(`ALTER TABLE \`customers\` CHANGE \`updated_at\` \`updated_at\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`customers\` CHANGE \`created_at\` \`created_at\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`customers\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`customers\` ADD \`id\` char(36) COLLATE "utf8mb4_unicode_ci" NOT NULL DEFAULT 'uuid()'`);
        await queryRunner.query(`ALTER TABLE \`customers\` ADD PRIMARY KEY (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`companies\` DROP INDEX \`IDX_b28b07d25e4324eee577de5496\``);
        await queryRunner.query(`ALTER TABLE \`companies\` CHANGE \`slug\` \`slug\` varchar(255) COLLATE "utf8mb4_unicode_ci" NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`companies\` CHANGE \`deleted_at\` \`deleted_at\` datetime(0) NULL`);
        await queryRunner.query(`ALTER TABLE \`companies\` CHANGE \`updated_at\` \`updated_at\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`companies\` CHANGE \`created_at\` \`created_at\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`companies\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`companies\` ADD \`id\` char(36) COLLATE "utf8mb4_unicode_ci" NOT NULL DEFAULT 'uuid()'`);
        await queryRunner.query(`ALTER TABLE \`companies\` ADD PRIMARY KEY (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`bank_accounts\` DROP COLUMN \`company_id\``);
        await queryRunner.query(`ALTER TABLE \`bank_accounts\` ADD \`company_id\` char(36) COLLATE "utf8mb4_unicode_ci" NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`bank_accounts\` CHANGE \`deleted_at\` \`deleted_at\` datetime(0) NULL`);
        await queryRunner.query(`ALTER TABLE \`bank_accounts\` CHANGE \`updated_at\` \`updated_at\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`bank_accounts\` CHANGE \`created_at\` \`created_at\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`bank_accounts\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`bank_accounts\` ADD \`id\` char(36) COLLATE "utf8mb4_unicode_ci" NOT NULL DEFAULT 'uuid()'`);
        await queryRunner.query(`ALTER TABLE \`bank_accounts\` ADD PRIMARY KEY (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`company_id\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`company_id\` char(36) COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`role\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`role\` varchar(50) COLLATE "utf8mb4_unicode_ci" NOT NULL DEFAULT 'customer'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`deleted_at\` \`deleted_at\` datetime(0) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`updated_at\` \`updated_at\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`created_at\` \`created_at\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`id\` char(36) COLLATE "utf8mb4_unicode_ci" NOT NULL DEFAULT 'uuid()'`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD PRIMARY KEY (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`payments\` DROP COLUMN \`type\``);
        await queryRunner.query(`DROP INDEX \`REL_d2b08509989c8a9869b417f48f\` ON \`company_sms_settings\``);
        await queryRunner.query(`DROP TABLE \`company_sms_settings\``);
        await queryRunner.query(`CREATE UNIQUE INDEX \`UQ_company_mail_settings_company\` ON \`company_mail_settings\` (\`company_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`UQ_paytr_settings_company\` ON \`company_paytr_settings\` (\`company_id\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_paytr_settings_company\` ON \`company_paytr_settings\` (\`company_id\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_notifications_user\` ON \`notifications\` (\`user_id\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_notifications_customer\` ON \`notifications\` (\`customer_id\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_transportation_jobs_customer\` ON \`transportation_jobs\` (\`customer_id\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_transportation_jobs_company\` ON \`transportation_jobs\` (\`company_id\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_transportation_job_staff_user\` ON \`transportation_job_staff\` (\`user_id\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_transportation_job_staff_job\` ON \`transportation_job_staff\` (\`transportation_job_id\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_warehouses_company\` ON \`warehouses\` (\`company_id\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_rooms_warehouse\` ON \`rooms\` (\`warehouse_id\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_items_room\` ON \`items\` (\`room_id\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_items_contract\` ON \`items\` (\`contract_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`UQ_contracts_number\` ON \`contracts\` (\`contract_number\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_contracts_room\` ON \`contracts\` (\`room_id\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_contracts_customer\` ON \`contracts\` (\`customer_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`UQ_contract_staff\` ON \`contract_staff\` (\`contract_id\`, \`user_id\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_contract_staff_user\` ON \`contract_staff\` (\`user_id\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_contract_staff_contract\` ON \`contract_staff\` (\`contract_id\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_contract_monthly_prices_month\` ON \`contract_monthly_prices\` (\`month\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_contract_monthly_prices_contract\` ON \`contract_monthly_prices\` (\`contract_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`UQ_payments_number\` ON \`payments\` (\`payment_number\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_payments_contract\` ON \`payments\` (\`contract_id\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_customers_user\` ON \`customers\` (\`user_id\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_customers_company\` ON \`customers\` (\`company_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`UQ_companies_slug\` ON \`companies\` (\`slug\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_bank_accounts_company\` ON \`bank_accounts\` (\`company_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`UQ_users_email\` ON \`users\` (\`email\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_users_company\` ON \`users\` (\`company_id\`)`);
        await queryRunner.query(`ALTER TABLE \`company_mail_settings\` ADD CONSTRAINT \`FK_company_mail_settings_company\` FOREIGN KEY (\`company_id\`) REFERENCES \`companies\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`company_paytr_settings\` ADD CONSTRAINT \`FK_paytr_settings_company\` FOREIGN KEY (\`company_id\`) REFERENCES \`companies\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`notifications\` ADD CONSTRAINT \`FK_notifications_user\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`notifications\` ADD CONSTRAINT \`FK_notifications_customer\` FOREIGN KEY (\`customer_id\`) REFERENCES \`customers\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`transportation_jobs\` ADD CONSTRAINT \`FK_transportation_jobs_customer\` FOREIGN KEY (\`customer_id\`) REFERENCES \`customers\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`transportation_jobs\` ADD CONSTRAINT \`FK_transportation_jobs_company\` FOREIGN KEY (\`company_id\`) REFERENCES \`companies\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`transportation_job_staff\` ADD CONSTRAINT \`FK_transportation_job_staff_user\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`transportation_job_staff\` ADD CONSTRAINT \`FK_transportation_job_staff_job\` FOREIGN KEY (\`transportation_job_id\`) REFERENCES \`transportation_jobs\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`warehouses\` ADD CONSTRAINT \`FK_warehouses_company\` FOREIGN KEY (\`company_id\`) REFERENCES \`companies\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`rooms\` ADD CONSTRAINT \`FK_rooms_warehouse\` FOREIGN KEY (\`warehouse_id\`) REFERENCES \`warehouses\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`items\` ADD CONSTRAINT \`FK_items_room\` FOREIGN KEY (\`room_id\`) REFERENCES \`rooms\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`items\` ADD CONSTRAINT \`FK_items_contract\` FOREIGN KEY (\`contract_id\`) REFERENCES \`contracts\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`contracts\` ADD CONSTRAINT \`FK_contracts_sold_by_user\` FOREIGN KEY (\`sold_by_user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`contracts\` ADD CONSTRAINT \`FK_contracts_room\` FOREIGN KEY (\`room_id\`) REFERENCES \`rooms\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`contracts\` ADD CONSTRAINT \`FK_contracts_customer\` FOREIGN KEY (\`customer_id\`) REFERENCES \`customers\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`contract_staff\` ADD CONSTRAINT \`FK_contract_staff_user\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`contract_staff\` ADD CONSTRAINT \`FK_contract_staff_contract\` FOREIGN KEY (\`contract_id\`) REFERENCES \`contracts\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`contract_monthly_prices\` ADD CONSTRAINT \`FK_contract_monthly_prices_contract\` FOREIGN KEY (\`contract_id\`) REFERENCES \`contracts\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`payments\` ADD CONSTRAINT \`FK_payments_contract\` FOREIGN KEY (\`contract_id\`) REFERENCES \`contracts\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`customers\` ADD CONSTRAINT \`FK_customers_user\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`customers\` ADD CONSTRAINT \`FK_customers_company\` FOREIGN KEY (\`company_id\`) REFERENCES \`companies\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`bank_accounts\` ADD CONSTRAINT \`FK_bank_accounts_company\` FOREIGN KEY (\`company_id\`) REFERENCES \`companies\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD CONSTRAINT \`FK_users_company\` FOREIGN KEY (\`company_id\`) REFERENCES \`companies\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

}
